name: website

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: |
          date > _index.md
          echo $GITHUB_PAT
        env:
          GITHUB_PAT: ${{ secrets.GIT_ACTIONS_TOKEN }}
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: master
          build_dir: .
        env:
          GITHUB_PAT: ${{ secrets.GIT_ACTIONS_TOKEN }}
